package com.bassamkhafagy.hafez.util

object Constant {
    const val HAFEZ_DATABASE_NAME = "HAFEZ_DATABASE_NAME"
    const val SHUYUKH_DATABASE_TABLE_NAME = "SHUYUKH_DATABASE_TABLE_NAME"
    const val STUDENTS_DATABASE_TABLE_NAME = "STUDENTS_DATABASE_TABLE_NAME"
    const val SORA_COMPLETE_DATABASE_TABLE_NAME = "SORA_COMPLETE_DATABASE_TABLE_NAME"
}